### PR TITLE
Remove non idl logos

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by mattijn** [comment]
I like the academic affiliations. I think it's a powerful asset of the Vega project. Can you use your Carnegie-Mellon affiliation? Maybe we can include it as well.

**Comment by domoritz** [comment]
Sure, we can include CMU. I just feel it might make Vega less inclusive since we prioritize some people's affiliations. Like, why don't we include UBC for @joelostblom?

**Comment by mattijn** [comment]
I used the affiliation mentioned in https://github.com/vega/.github/blob/main/project-docs/ADMINS.md.

As a non-affiliate it is quite satisfying to participate in a project with free time that _enables science_, and not is intended as _free labour_ for private organizations.

For that reason, it would be great if @joelostblom also can use his affiliation.

**Comment by jonmmease** [comment]
> I used the affiliation mentioned in https://github.com/vega/.github/blob/main/project-docs/ADMINS.md.

But what about commercial affiliations?  I'd be worried about the precedent of promoting the logos of the organization / company affiliations of members of the steering committee, as this creates a PR incentive for people to want to join the steering committee.

I would be in favor of keeping only IDL, since this was the birth place of the Vega ecosystem

**Comment by mattijn** [comment]
Hm, you are right. There is not a perfect answer here. I can agree with what you propose.

**Comment by domoritz** [comment]
Thanks for the input. I updated to keep the IDL logo.

**Review by mattijn — APPROVED** [review]

**Pull request merged**
