### PR TITLE
updating vega projects page

### PR DESCRIPTION
**Pull request by mattijn**
This updates the landings page to incorporate all projects mentioned within the charter.

After this PR it will look as such:

image

I've no time to incorporate additional changes today. If required. Please take over from here, so we have this updated as part of our numfocus application.

### CODE REVIEW

**Review by binste — APPROVED** [review]
Looks great! Cool to have a single page to direct people to to learn more about the "Vega project"! 🥳

**Comment by arvind** [comment]
This looks fantastic!! Thank you @mattijn!

**Comment by domoritz** [comment]
Thanks for the updates. We should compress the images a bit but I can do that in a follow up pull request. 

The IDL/MIT logos feel a bit out of place now since they are just a subset of the places where projects are being developed. Should we remove them? O

**Comment by domoritz** [comment]
@jonmmease Should we say VlConvert or Vega Convert? The website says the latter now.

**Comment by jonmmease** [comment]
It should be VlConvert, thanks for catching that!

**Comment by domoritz** [comment]
Fixed

**Pull request merged**
